#ifndef GUI_ELEMENT_ID
#define GUI_ELEMENT_ID

enum GUI_Element_ID{
	BUTTON_EXIT = wxID_HIGHEST +1,
	BUTTON_RESTART,
	BUTTON_SHUTDOWN,
	TIMER,
	COMBO_BOX_NETWORK,
	BUTTON_SORT_PROC_NAME,
	BUTTON_SORT_PROC_PID,
	BUTTON_SORT_PROC_CPU,
	BUTTON_SORT_PROC_RAM,
	BUTTON_CONNECT,
	BUTTON_USER_MANAGEMENT_SUMBIT_CHANGES,
	BUTTON_USER_MANAGEMENT_REFRESH,
	BUTTON_SYSTEM_MANAGEMENT_SUMBIT_CHANGES,
	BUTTON_SYSTEM_MANAGEMENT_REFRESH
};

#endif