#ifndef GUI_ELEMENT_ID
#define GUI_ELEMENT_ID

enum GUI_Element_ID{
	BUTTON_EXIT = wxID_HIGHEST +1,
	BUTTON_RESTART,
	BUTTON_SHUTDOWN,
	TIMER,
	MP_WINDOW,
	COMBO_BOX_NETWORK,
	BUTTON_SORT_PROC_NAME,
	BUTTON_SORT_PROC_PID,
	BUTTON_SORT_PROC_CPU,
	BUTTON_SORT_PROC_RAM,
	BUTTON_CONNECT
};

#endif